import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarNav from "@/Layout/SidebarNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col max-h-screen sm:h-auto sm:flex-row`}
      >
        <SidebarNav />
        <div className="flex-1 overflow-y-auto max-h-screen scrollbar-mobile md:scrollbar-desktop">
          <div className="p-4 max-w-6xl">{children}</div>
        </div>
      </body>
    </html>
  );
}
